# Site settings

title: Nick Zuber | Software Engineer
email: zuber.nicholas@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Nick Zuber is a sofware engineer for the web and mobile applications based out of the Boston area. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nickzuber.com"

twitter_username: nick_zuber
github_username:  nickzuber
full_name: Nick Zuber

job_title: Software Engineer Intern
job_segue: working at
job_place: Robin

permalink: /:categories/:title

# Build settings
markdown: kramdown
source: src
destination: public

gems:
- octopress-minify-html

sass:
  style: :compressed

exclude:
- node_modules
- package.json
